[package]
name = "buffer_hopper"
version = "0.1.0"
edition = "2021"

[dependencies]


[dev-dependencies]
rand = "0.8.5"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "speed"
harness = false