[package]
name = "audio_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
rustfft = "6.2.0"

[dev-dependencies]
rand = "0.8.5"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "fft_speed"
harness = false
