[alias]
rb = "run --bin main"
rrb = "run --release --bin main"
bbr = "build --release --bin main"
lint = "clippy --all-features -- -D clippy::pedantic"
"lint:fix" = "clippy --all-features --fix --allow-staged -- -D clippy::pedantic"
format = "fmt --all --check"
"format:fix" = "fmt --all"
